SET VERIFY OFF
SET FEEDBACK ON
SET DEFINE ON

CREATE TABLE MIKULAB4 (
	ID NUMBER(10) NOT NULL PRIMARY KEY,
	LAST_NAME VARCHAR2(20),
	BIRTHDAY DATE,
	GENDER VARCHAR2(1),
	MATH NUMBER(1),
	INFO NUMBER(1),
	FORLAN NUMBER(1),
	GRADE NUMBER(3,2),
	BASESCHOLARSHIP NUMBER(10,2),
	SCHOLARSHIP NUMBER(10,2)
);

INSERT INTO MIKULAB4 (ID, LAST_NAME, BIRTHDAY, GENDER, MATH, INFO, FORLAN, GRADE, BASESCHOLARSHIP, SCHOLARSHIP)
SELECT "id", "last_name", "birthday", "GENDER", "math", "info", "forlan", NULL, NULL, NULL
	FROM STUDENTS;
COMMIT;

UPDATE MIKULAB4
SET GRADE = (MATH + INFO + FORLAN) / 3;

ACCEPT NEWBASESCHOLARSHIP NUMBER PROMPT 'Введите значение базовой стипендии: '

UPDATE MIKULAB4
SET BASESCHOLARSHIP = &NEWBASESCHOLARSHIP;

UPDATE MIKULAB4
SET	SCHOLARSHIP = CASE
		WHEN GRADE >= 4.5 THEN &NEWBASESCHOLARSHIP * 1.5
		WHEN GRADE >= 3.5 AND GRADE < 4.5 THEN &NEWBASESCHOLARSHIP * 1.25
		WHEN GRADE >= 2.5 AND GRADE < 3.5 THEN &NEWBASESCHOLARSHIP
		ELSE 0
	END
;

COMMIT;
