spring.application.name=server
spring.profiles.active=${SERVER_PROFILE:}
spring.profiles.default=dev
server.port=${APP_SERVER_PORT:8080}

spring.datasource.driver-class-name=${APP_DB_DRIVER:org.h2.Driver}
spring.datasource.url=${APP_DB_URL:jdbc:h2:mem:db}
spring.datasource.username=${APP_DB_USER:sa}
spring.datasource.password=${APP_DB_PASSWORD:sa}

spring.jpa.open-in-view=true