spring.application.name=client
server.port=${APP_CLIENT_PORT:5050}
spring.profiles.active=${CLIENT_PROFILE:}
spring.profiles.default=dev

logging.level.org.atmosphere=warn
vaadin.launch-browser=true
vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,com.client
vaadin.devmode.copilot.enabled=false